from __future__ import annotations

import argparse
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path


TOOLS = {
    "git": "Required for version control and change evidence.",
    "rg": "Recommended for fast repository search.",
    "python3": "Required for workflow-pack scripts.",
    "node": "Recommended for frontend projects and markdown tooling.",
    "corepack": "Recommended for pnpm-managed frontend projects.",
    "pandoc": "Recommended for converting docx/html product documents to Markdown.",
    "lychee": "Recommended for link verification.",
}


@dataclass
class ToolStatus:
    name: str
    present: bool
    version: str
    note: str


def collect_status() -> list[ToolStatus]:
    statuses: list[ToolStatus] = []
    for tool, note in TOOLS.items():
        path = shutil.which(tool)
        version = ""
        if path:
            version = _version(tool)
        statuses.append(ToolStatus(tool, bool(path), version, note))
    return statuses


def write_repair_plan(target: Path, statuses: list[ToolStatus]) -> Path:
    missing = [status for status in statuses if not status.present]
    path = target / ".governance/env-repair.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Environment Repair Plan",
        "",
        "This file is generated by `scripts/check_env.py --repair`.",
        "",
        "## Missing Tools",
        "",
    ]
    if missing:
        for status in missing:
            lines.append(f"- `{status.name}`: {status.note}")
    else:
        lines.append("- None")
    lines.extend(
        [
            "",
            "## Safe Local Repairs",
            "",
            "- `.governance/` directory exists.",
            "- No system package installation was attempted automatically.",
            "",
            "## Manual Repairs",
            "",
            "- Install system tools with your OS package manager when required.",
            "- Install `pandoc` before converting DOCX or HTML product documents.",
            "- Install `lychee` before enforcing strict link checks.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def _version(tool: str) -> str:
    candidates = ([tool, "--version"], [tool, "-V"])
    for cmd in candidates:
        try:
            result = subprocess.run(cmd, check=False, text=True, capture_output=True, timeout=5)
        except Exception:
            continue
        output = (result.stdout or result.stderr).strip().splitlines()
        if output:
            return output[0][:120]
    return "installed"


def main() -> int:
    parser = argparse.ArgumentParser(description="Check local tools used by the governance workflow pack.")
    parser.add_argument("--strict", action="store_true", help="Return non-zero when recommended tools are missing.")
    parser.add_argument("--repair", action="store_true", help="Write a local environment repair plan.")
    parser.add_argument("--target", default=".", help="Target directory for repair artifacts.")
    args = parser.parse_args()

    missing: list[str] = []
    statuses = collect_status()
    for status in statuses:
        mark = "OK" if status.present else "MISSING"
        print(f"{mark:7} {status.name:10} {status.version or status.note}")
        if not status.present:
            missing.append(status.name)

    if missing:
        print("\nRepair guidance:")
        print("- Install missing system tools with your OS package manager.")
        print("- `pandoc` and `lychee` are optional during early product archiving but required for strict docs CI.")
        print("- Re-run `python3 scripts/check_env.py --strict` before declaring the workflow environment ready.")
    if args.repair:
        path = write_repair_plan(Path(args.target), statuses)
        print(f"\nWrote repair plan: {path}")
    return 1 if args.strict and missing else 0


if __name__ == "__main__":
    raise SystemExit(main())
